import React from 'react';
import { FarmerReport } from '../types';
import { ArrowLeft } from 'lucide-react';

interface ReportCardProps {
  report: FarmerReport;
  onBack: () => void;
}

const ReportCard: React.FC<ReportCardProps> = ({ report, onBack }) => {

  return (
    <div className="space-y-6 pb-8">
      {/* Navigation Header - Hidden in Print */}
      <div className="flex items-center justify-between sticky top-0 bg-slate-50 z-10 py-2 no-print">
        <button onClick={onBack} className="p-2 hover:bg-slate-200 rounded-full transition-colors">
          <ArrowLeft className="w-6 h-6 text-slate-700" />
        </button>
        <h2 className="text-xl font-bold text-slate-800">Farmer Report Card</h2>
        <div className="w-10"></div> {/* Spacer */}
      </div>

      {/* Printable Report Section */}
      <div id="report-card" className="bg-white border-2 border-green-600 rounded-xl overflow-hidden shadow-lg print:border-none print:shadow-none">
        {/* Report Header */}
        <div className="bg-green-700 text-white p-4 print:bg-white print:text-black print:border-b-2 print:border-green-700">
          <div className="flex justify-between items-center">
            <h1 className="text-lg font-bold">Kisan Plant Doctor Report</h1>
            <span className="text-sm opacity-80 print:text-black">{new Date(report.timestamp).toLocaleDateString()}</span>
          </div>
        </div>

        {/* Report Content */}
        <div className="p-6 space-y-4">
          {report.imageUri && (
             <div className="w-full h-48 bg-slate-100 rounded-lg overflow-hidden mb-4 border border-slate-200 print:h-auto print:max-h-64">
                <img src={report.imageUri} alt="Crop" className="w-full h-full object-cover print:object-contain" />
             </div>
          )}

          <div className="grid grid-cols-2 gap-4">
            <div>
              <p className="text-xs text-slate-500 uppercase font-semibold">Crop Detected</p>
              <p className="font-medium text-lg">{report.crop}</p>
            </div>
             <div>
              <p className="text-xs text-slate-500 uppercase font-semibold">Diagnosis</p>
              <p className="font-bold text-red-600 text-lg">{report.diagnosis.disease_name}</p>
            </div>
          </div>

          <div className="border-t border-slate-100 pt-3">
             <p className="text-xs text-slate-500 uppercase font-semibold mb-1">Recommended Treatment</p>
             <ul className="text-sm space-y-1 text-slate-700 list-none pl-1">
                {report.diagnosis.treatment_steps.map((step, i) => (
                  <li key={i} className="flex gap-2">
                    <span className="font-bold text-green-700">{i+1}.</span>
                    <span>{step}</span>
                  </li>
                ))}
             </ul>
          </div>
          
           <div className="border-t border-slate-100 pt-3">
             <p className="text-xs text-slate-500 uppercase font-semibold mb-1">Prevention</p>
             <ul className="text-sm space-y-1 text-slate-700 list-disc pl-4">
                {report.diagnosis.prevention_tips.slice(0, 2).map((tip, i) => (
                  <li key={i}>{tip}</li>
                ))}
             </ul>
          </div>

          <div className="bg-slate-50 p-3 rounded-lg text-xs text-slate-500 italic text-center print:bg-white print:border print:border-slate-200">
            Generated by Kisan Plant Doctor AI. Verify with a human expert before applying chemicals.
          </div>
        </div>
      </div>
    </div>
  );
};

export default ReportCard;